[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd l2-educa-backend && npm ci"]

[phases.build]
cmds = ["cd l2-educa-backend && npm run build"]

[start]
cmd = "cd l2-educa-backend && npm start"

